### ISSUE TITLE
这SDK真难用, 代码写的完全不符合NODE的规范啊!

### ISSUE THREAD

**Issue by suzukua** [GeeTeam/gt-node-sdk#1]
可以把http请求的error事件直接抛出来吗?!!!!
代码写的完全不符合NODE的规范啊!

**Comment by suzukua** [comment]
我去!! 得 , 我自己写一个算了.

**Comment by zhangcx93** [comment]
你把需要改进的地方具体提一下

**Comment by suzukua** [comment]
几分钟就改好了, 等下给你们发pr

**Comment by suzukua** [comment]
按照现在SDK的版本很难区分到底是错误引起的验证码错误还是验证码输入错误啊.个人觉得不应该混在一起.

**Comment by zhangcx93** [comment]
已经更新了0.4.0，用你改的这个方法确实比较好地区分了错误和验证错误。感谢支持。
