### ISSUE TITLE
所以Node版没有现成的failback嘛 >.<

### ISSUE THREAD

**Issue by SCLeoX** [GeeTeam/gt-node-sdk#11]
应该不是我没看到而是真的没有吧。就是Node生成图片麻烦才用的极验哇，现在failback就是去图形验证码还是绕不开啊。。。（不过我的网站宕机时间应该比极验长多了把。。雾

**Comment by guguji** [comment]
宕机了可以加载离线验证码，只不过就不能去极验服务器验证一次而已，当然你也可以failback就生成自己的图形验证码。

**Comment by lhtin** [comment]
抱歉，目前Node SDK没有failback功能。您可以先用着，因为只有极验服务器宕机了才会进入failback，宕机的概率很小。然后我们会尽快加上failback功能，这样就可以选择failback模式下的拖动验证，而不需要自备用一套验证

**Comment by SCLeoX** [comment]
好吧，那这个 Issue 先挂着，修好了再关 >.>

**Comment by lhtin** [comment]
很高兴的告诉大家，我们已经给node-sdk添加了failback功能，同时使用方式有些改变。详细的说明请移步README.md
