### ISSUE TITLE
帮忙看下这是我哪里问题

### ISSUE THREAD

**Issue by sisilai** [GeeTeam/gt-node-sdk#5]
![image](https://cloud.githubusercontent.com/assets/11345742/13195880/09c2a536-d7f8-11e5-9a0b-4b173b1dce17.png)

**Comment by leizongmin** [comment]
请不要在NPM上安装`geetest`模块，直接复制这个项目里面的`gt-sdk.js`文件或者自己手写一个更加靠谱
刚刚踩完一轮坑，歇一会再踩，对你的遭遇深表同情

**Comment by lhtin** [comment]
现在可以在npm上安装该模块的
